import { NavLink, Category, Job, Company, Article, RecruitmentEvent, BlogPost, CompanyProfile, MisiCuanOffer, PelatihanInfo, Major, MisiSubmission, AdminUser, Tag } from './types';

export const NAV_LINKS: NavLink[] = [
  { name: 'Home', href: '#' },
  { name: 'MT/ODP', href: '#' },
  { name: 'BUMN', href: '#' },
  { name: 'Instansi', href: '#' },
  { name: 'Fresh Grad', href: '#' },
  { name: 'Intern', href: '#' },
  { name: 'Event', href: '#' },
  { name: 'Misi Cuan', href: '#' },
  { name: 'Komunitas', href: '#' },
  { name: 'Pasang Iklan', href: '#', isSpecial: true },
  { name: 'Blog', href: '#' },
  { name: 'Favorit', href: '#', icon: 'far fa-bookmark' },
];

export const CATEGORIES: Category[] = [
  { name: 'BUMN', count: 120, icon: 'fas fa-building', iconBgColor: 'bg-blue-100', iconTextColor: 'text-primary' },
  { name: 'Swasta', count: 215, icon: 'fas fa-briefcase', iconBgColor: 'bg-green-100', iconTextColor: 'text-green-600' },
  { name: 'CASN', count: 78, icon: 'fas fa-user-shield', iconBgColor: 'bg-yellow-100', iconTextColor: 'text-yellow-600' },
  { name: 'Misi Cuan', count: 3, icon: 'fas fa-coins', iconBgColor: 'bg-orange-100', iconTextColor: 'text-orange-600' },
  { name: 'Instansi', count: 56, icon: 'fas fa-landmark', iconBgColor: 'bg-purple-100', iconTextColor: 'text-purple-600' },
  { name: 'Fresh Grad', count: 95, icon: 'fas fa-user-graduate', iconBgColor: 'bg-red-100', iconTextColor: 'text-red-600' },
];

export const INITIAL_JOBS: Job[] = [
    { 
        id: 1, 
        title: 'Staff Administrasi', 
        company: 'PT Dahana (Persero)',
        companySlug: 'pt-dahana', 
        logo: 'https://picsum.photos/40/40?random=10', 
        location: 'Jakarta Pusat',
        province: 'DKI JAKARTA',
        city: 'KOTA ADM. JAKARTA PUSAT',
        type: 'Full Time', 
        category: 'BUMN', 
        categoryColor: 'blue', 
        description: 'Sebagai Staff Administrasi, Anda akan bertanggung jawab untuk mengelola dokumen, mengatur jadwal, dan memberikan dukungan administratif untuk memastikan kelancaran operasional kantor.', 
        posted: '2 hari yang lalu', 
        education: 'Strata 1',
        experience: 'Minimal 2 tahun',
        tags: ['BUMN', 'Administrasi', 'S1', 'Microsoft Office', 'Organisasi'],
        majors: ['Administrasi Perkantoran', 'Manajemen', 'Ilmu Komunikasi', 'Sekretaris', 'Semua Jurusan'],
        qualifications: [
            'Pendidikan minimal S1 semua jurusan, diutamakan Administrasi Perkantoran.',
            'Pengalaman minimal 2 tahun di bidang administrasi.',
            'Mahir menggunakan Microsoft Office (Word, Excel, PowerPoint).',
            'Memiliki kemampuan komunikasi dan organisasi yang baik.',
            'Teliti, cekatan, dan mampu bekerja di bawah tekanan.'
        ],
        benefits: [
            'Asuransi Kesehatan (BPJS Kesehatan & Asuransi Swasta).',
            'Tunjangan Hari Raya (THR).',
            'Program pensiun.',
            'Cuti tahunan 12 hari.',
            'Kesempatan pengembangan diri melalui pelatihan.'
        ],
        howToApply: "Kirimkan CV terbaru dan surat lamaran Anda melalui tombol 'Lamar Sekarang' di atas. Pastikan semua dokumen yang dilampirkan dalam format PDF. Hanya kandidat yang memenuhi kualifikasi yang akan kami hubungi untuk proses seleksi selanjutnya.",
        aboutCompany: "PT Dahana (Persero) adalah Badan Usaha Milik Negara (BUMN) yang bergerak di bidang industri bahan peledak. Kami menyediakan layanan peledakan terpadu untuk sektor pertambangan umum, kuari dan konstruksi, serta minyak dan gas.",
        videoEmbedUrl: "https://www.youtube.com/embed/videoseries?list=PL4cUxeGkcC9g_ytbN_8thTT4a6dJv1b1G"
    },
    { 
        id: 2, 
        title: 'Supervisor Produksi', 
        company: 'PT Japfa Comfeed Indonesia',
        companySlug: 'japfa-comfeed',
        logo: 'https://picsum.photos/40/40?random=11', 
        location: 'Surabaya', 
        province: 'JAWA TIMUR',
        city: 'KOTA SURABAYA',
        type: 'Full Time', 
        category: 'Manufaktur', 
        categoryColor: 'orange', 
        description: 'Bertanggung jawab untuk mengawasi seluruh proses produksi, memastikan target kualitas dan kuantitas tercapai, serta memimpin tim produksi secara efektif dan efisien.', 
        posted: '1 hari yang lalu', 
        education: 'Strata 1',
        experience: 'Minimal 3 tahun',
        tags: ['SWASTA', 'Manufaktur', 'Pakan Ternak', 'Produksi', 'S1', 'Kepemimpinan', 'GMP', 'HACCP'],
        majors: ['Teknik Industri', 'Teknik Mesin', 'Teknologi Pangan', 'Teknik Kimia'],
        qualifications: [
            'Pendidikan minimal S1 Teknik Industri, Teknik Mesin, atau setara.',
            'Pengalaman minimal 3 tahun sebagai Supervisor di industri manufaktur pakan ternak/makanan.',
            'Memahami prinsip-prinsip GMP, HACCP, dan ISO 22000.',
            'Memiliki jiwa kepemimpinan yang kuat dan mampu memotivasi tim.',
            'Bersedia bekerja dengan sistem shift.'
        ],
        benefits: [
            'Gaji kompetitif.',
            'Bonus kinerja tahunan.',
            'Asuransi kesehatan lengkap untuk karyawan dan keluarga.',
            'Makan siang disediakan.',
            'Tunjangan transportasi.'
        ],
        howToApply: "Silakan kirimkan lamaran lengkap Anda ke email recruitment@japfacomfeed.co.id dengan subjek 'Supervisor Produksi - Surabaya'. Lampirkan CV, ijazah, dan transkrip nilai. Lamaran diterima paling lambat 2 minggu setelah iklan ini tayang.",
        aboutCompany: "PT Japfa Comfeed Indonesia Tbk adalah salah satu perusahaan agribisnis terbesar di Indonesia, dengan lini bisnis utama meliputi pembuatan pakan ternak, peternakan ayam, pengolahan unggas, dan budidaya perairan."
    },
    { 
        id: 3, 
        title: 'Teknisi Maintenance', 
        company: 'PT GS Battery',
        companySlug: 'gs-battery',
        logo: 'https://picsum.photos/40/40?random=12', 
        location: 'Bekasi', 
        province: 'JAWA BARAT',
        city: 'KAB. BEKASI',
        type: 'Full Time', 
        category: 'Manufaktur', 
        categoryColor: 'orange', 
        description: 'Melakukan kegiatan perawatan preventif dan korektif terhadap mesin-mesin produksi untuk memastikan operasional berjalan lancar dan meminimalkan downtime.', 
        posted: '3 hari yang lalu', 
        education: 'Diploma III',
        experience: 'Minimal 1 tahun',
        tags: ['SWASTA', 'Manufaktur', 'Otomotif', 'Maintenance', 'Teknik Elektro', 'Teknik Mesin', 'D3', 'PLC'],
        majors: ['Teknik Elektro', 'Teknik Mesin', 'Mekatronika', 'Teknik Listrik'],
        qualifications: [
            'Lulusan D3 Teknik Elektro (Arus Kuat) atau Teknik Mesin.',
            'Pengalaman minimal 1 tahun sebagai teknisi maintenance di pabrik.',
            'Memahami sistem PLC dan pneumatik menjadi nilai tambah.',
            'Mampu membaca wiring diagram dan gambar teknik.',
            'Tidak buta warna dan siap bekerja dalam tim.'
        ],
        benefits: [
            'BPJS Kesehatan & Ketenagakerjaan.',
            'Uang lembur sesuai peraturan.',
            'Seragam kerja dan APD lengkap.',
            'Program training teknis.',
            'Lingkungan kerja yang aman dan sehat.'
        ],
        howToApply: "Daftarkan diri Anda melalui portal karir resmi kami di www.gs.astra.co.id/careers. Ikuti petunjuk pendaftaran dan unggah dokumen yang diperlukan. Proses seleksi tidak dipungut biaya apapun.",
        aboutCompany: "PT GS Battery merupakan bagian dari Astra Otoparts Tbk dan menjadi pelopor dalam produksi aki di Indonesia. Produk kami, aki GS Astra, telah menjadi pilihan utama bagi jutaan pengendara di tanah air."
    },
    { 
        id: 4, 
        title: 'Staff Accounting', 
        company: 'PT Waskita Karya (Persero)',
        companySlug: 'waskita-karya',
        logo: 'https://picsum.photos/40/40?random=13', 
        location: 'Jakarta Timur', 
        province: 'DKI JAKARTA',
        city: 'KOTA ADM. JAKARTA TIMUR',
        type: 'Full Time', 
        category: 'BUMN', 
        categoryColor: 'blue', 
        description: 'Menyusun laporan keuangan, melakukan rekonsiliasi bank, dan memastikan kepatuhan terhadap peraturan perpajakan yang berlaku.', 
        posted: '5 hari yang lalu', 
        education: 'Strata 1',
        experience: 'Fresh Graduate',
        tags: ['BUMN', 'Konstruksi', 'Akuntansi', 'Pajak', 'S1', 'Fresh Graduate', 'Brevet'],
        majors: ['Akuntansi', 'Manajemen Keuangan', 'Perpajakan'],
        qualifications: [
            'Lulusan S1 Akuntansi dengan IPK minimal 3.00.',
            'Fresh graduate dipersilakan melamar.',
            'Memiliki sertifikat Brevet A & B menjadi nilai tambah.',
            'Memahami standar akuntansi keuangan (PSAK).',
            'Jujur, teliti, dan bertanggung jawab.'
        ],
        benefits: [
            'Gaji pokok dan tunjangan.',
            'Asuransi kesehatan.',
            'Jenjang karir yang jelas.',
            'Lingkungan kerja yang dinamis.',
            'Program pengembangan karyawan.'
        ],
        howToApply: "Kunjungi halaman karir di situs resmi Waskita Karya (waskita.co.id/career) dan ikuti proses pendaftaran online. Pendaftaran dibuka hingga akhir bulan ini.",
        aboutCompany: "PT Waskita Karya (Persero) Tbk adalah salah satu BUMN konstruksi terkemuka di Indonesia yang telah menyelesaikan berbagai proyek infrastruktur berskala besar, seperti jalan tol, jembatan, bandara, dan bendungan."
    },
    { 
        id: 5, 
        title: 'Customer Service Representative', 
        company: 'Telkom Indonesia',
        companySlug: 'telkom-indonesia',
        logo: 'https://picsum.photos/40/40?random=14', 
        location: 'Seluruh Indonesia',
        province: 'Seluruh Indonesia',
        city: 'Online',
        type: 'Full Time', 
        category: 'BUMN', 
        categoryColor: 'blue', 
        description: 'Memberikan layanan pelanggan yang luar biasa melalui berbagai saluran digital. Posisi ini sepenuhnya remote dan terbuka untuk kandidat dari seluruh Indonesia.', 
        posted: '1 hari yang lalu', 
        education: 'SMA/SMK',
        experience: 'Minimal 1 tahun',
        tags: ['BUMN', 'Customer Service', 'Remote', 'SMA', 'Komunikasi'],
        majors: ['Semua Jurusan'],
        qualifications: [
            'Pendidikan minimal SMA/SMK atau sederajat.',
            'Pengalaman minimal 1 tahun sebagai Customer Service.',
            'Memiliki kemampuan komunikasi yang sangat baik, baik lisan maupun tulisan.',
            'Sabar, empati, dan berorientasi pada solusi.',
            'Memiliki koneksi internet yang stabil di rumah.'
        ],
        benefits: [
            'Gaji kompetitif.',
            'Insentif berdasarkan kinerja.',
            'Asuransi kesehatan.',
            'Bekerja dari rumah (Work From Home).',
            'Tunjangan internet.'
        ],
        howToApply: "Lamar melalui platform rekrutmen online kami di recruitment.telkom.co.id. Buat akun, lengkapi profil Anda, dan cari posisi 'Customer Service Representative (Remote)'.",
        aboutCompany: "PT Telkom Indonesia (Persero) Tbk adalah BUMN yang bergerak di bidang jasa layanan teknologi informasi dan komunikasi (TIK) dan jaringan telekomunikasi di Indonesia."
    },
    { 
        id: 6, 
        title: 'Analis Keuangan', 
        company: 'Bank Mandiri',
        companySlug: 'bank-mandiri',
        logo: 'https://picsum.photos/40/40?random=15', 
        location: 'Bandung', 
        province: 'JAWA BARAT',
        city: 'KOTA BANDUNG',
        type: 'Full Time', 
        category: 'BUMN', 
        categoryColor: 'blue', 
        description: 'Melakukan analisis mendalam terhadap data keuangan untuk mendukung pengambilan keputusan strategis, serta memantau kinerja portofolio kredit.', 
        posted: '6 hari yang lalu', 
        education: 'Strata 1',
        experience: 'Minimal 2 tahun',
        tags: ['BUMN', 'Perbankan', 'Keuangan', 'Analisis', 'S1', 'Bandung'],
        majors: ['Manajemen Keuangan', 'Akuntansi', 'Ekonomi', 'Perbankan', 'Statistika'],
        qualifications: [
            'Lulusan S1 Keuangan, Akuntansi, atau Ekonomi.',
            'Pengalaman minimal 2 tahun di bidang analisis keuangan atau kredit di industri perbankan.',
            'Kemampuan analisis dan pemecahan masalah yang kuat.',
            'Menguasai Microsoft Excel tingkat lanjut.',
            'Memiliki pemahaman yang baik tentang produk perbankan.'
        ],
        benefits: [
            'Paket remunerasi yang menarik.',
            'Asuransi jiwa dan kesehatan.',
            'Fasilitas pinjaman karyawan.',
            'Peluang karir di seluruh Indonesia.',
            'Bonus tahunan.'
        ],
        howToApply: "Kirimkan CV Anda ke karir.bandung@bankmandiri.co.id dengan subjek 'Analis Keuangan'. Hanya kandidat terpilih yang akan dihubungi.",
        aboutCompany: "PT Bank Mandiri (Persero) Tbk adalah salah satu bank terbesar di Indonesia dalam hal aset, pinjaman, dan simpanan. Kami berkomitmen untuk memberikan solusi keuangan terbaik bagi nasabah kami."
    },
    { 
        id: 7, 
        title: 'Digital Marketing Specialist', 
        company: 'Gojek',
        companySlug: 'gojek',
        logo: 'https://picsum.photos/40/40?random=16', 
        location: 'Yogyakarta', 
        province: 'DAERAH ISTIMEWA YOGYAKARTA',
        city: 'KOTA YOGYAKARTA',
        type: 'Full Time', 
        category: 'Swasta', 
        categoryColor: 'green', 
        description: 'Merancang dan mengeksekusi kampanye pemasaran digital di berbagai platform (SEO, SEM, Social Media) untuk meningkatkan akuisisi pengguna dan engagement.', 
        posted: '4 hari yang lalu', 
        education: 'Strata 1',
        experience: 'Minimal 3 tahun',
        tags: ['SWASTA', 'Teknologi', 'Digital Marketing', 'SEO', 'SEM', 'S1', 'Yogyakarta'],
        majors: ['Marketing', 'Ilmu Komunikasi', 'Manajemen Bisnis', 'DKV', 'Sistem Informasi'],
        qualifications: [
            'Pengalaman minimal 3 tahun di bidang digital marketing.',
            'Keahlian yang terbukti dalam SEO, SEM (Google Ads), dan Social Media Marketing (Meta Ads, TikTok Ads).',
            'Mampu menganalisis data kampanye dan memberikan wawasan yang dapat ditindaklanjuti.',
            'Kreatif dan selalu mengikuti tren terbaru di dunia digital.',
            'Memiliki pengalaman dengan A/B testing dan optimisasi kampanye.'
        ],
        benefits: [
            'Gaji yang kompetitif dan opsi saham (ESOP).',
            'Asuransi kesehatan premium.',
            'Budget untuk pengembangan diri.',
            'Lingkungan kerja yang fleksibel dan inovatif.',
            'Tunjangan makan dan transportasi.'
        ],
        howToApply: "Lamar langsung melalui halaman karir Gojek di gojek.com/careers. Cari posisi 'Digital Marketing Specialist - Yogyakarta' dan ikuti petunjuknya.",
        aboutCompany: "Gojek adalah platform on-demand terkemuka di Asia Tenggara, menyediakan berbagai layanan mulai dari transportasi, pengiriman makanan, logistik, hingga pembayaran digital.",
        pdfEmbedUrl: "https://drive.google.com/file/d/1s_h_Od3Al945-P8i2e3a-m2K3k2lJk3F/preview"
    },
];


export const INITIAL_RECRUITMENT_EVENTS: RecruitmentEvent[] = [
  {
    id: 1,
    title: 'BUMN Career Fair 2024',
    organizer: 'Kementerian BUMN',
    date: '2024-08-15',
    time: '09:00 - 17:00 WIB',
    location: 'Jakarta Convention Center',
    province: 'DKI JAKARTA',
    city: 'KOTA ADM. JAKARTA PUSAT',
    type: 'Job Fair',
    isFeatured: true,
    image: 'https://picsum.photos/seed/event1/800/450',
    description: '<p>Job fair <b>terbesar</b> yang diikuti oleh puluhan perusahaan BUMN terkemuka. Bawa CV terbaikmu dan dapatkan kesempatan interview langsung di tempat!</p><p>Acara ini gratis dan terbuka untuk umum, mulai dari lulusan SMA/SMK hingga S2.</p>',
    participatingCompanies: [
      { name: 'Pertamina', logo: 'https://picsum.photos/80/40?random=1', slug: 'pertamina' },
      { name: 'Bank Mandiri', logo: 'https://picsum.photos/80/40?random=2', slug: 'bank-mandiri' },
      { name: 'Telkom Indonesia', logo: 'https://picsum.photos/80/40?random=3', slug: 'telkom-indonesia' },
      { name: 'PLN', logo: 'https://picsum.photos/80/40?random=4' },
      { name: 'KAI', logo: 'https://picsum.photos/80/40?random=5' }
    ],
    availablePositions: ['Management Trainee', 'Staf Teknik', 'Staf Keuangan', 'Analis Data', 'IT Support'],
    whatToBring: ['CV terbaru (beberapa rangkap)', 'Fotokopi Ijazah & Transkrip Nilai', 'Pas Foto 4x6', 'Alat Tulis'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.335728362635!2d106.80703867591879!3d-6.219890960920422!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f143e12c4221%3A0x1d94f25368a5c375!2sJakarta%20Convention%20Center%20(JCC)!5e0!3m2!1sen!2sid!4v1721380962386!5m2!1sen!2sid',
    mapDirectionUrl: 'https://maps.app.goo.gl/uC5aR2i8y7f8z7xQ9',
  },
  {
    id: 2,
    title: 'Walk-in Interview PT Maju Jaya',
    organizer: 'PT Maju Jaya Abadi',
    organizerSlug: 'pt-maju-jaya-abadi',
    date: '2024-08-20',
    time: '10:00 - 14:00 WIB',
    location: 'Kantor Pusat PT Maju Jaya, Surabaya',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    type: 'Walk-in Interview',
    isFeatured: false,
    image: 'https://picsum.photos/seed/event2/800/450',
    description: 'Kesempatan emas untuk posisi Sales & Marketing. Datang langsung dengan membawa CV lengkap dan berpakaian rapi.',
    availablePositions: ['Sales Executive', 'Marketing Associate', 'Telemarketing'],
    whatToBring: ['CV lengkap', 'Fotokopi KTP', 'Surat Lamaran Kerja'],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d253272.9348123548!2d112.56203197283256!3d-7.27584711385435!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd7fbf8381ac47f%3A0x3027a76e352be40!2sSurabaya%2C%20Surabaya%20City%2C%20East%20Java!5e0!3m2!1sen!2sid!4v1721381090176!5m2!1sen!2sid',
    mapDirectionUrl: 'https://maps.app.goo.gl/uC5aR2i8y7f8z7xQ9',
  },
   {
    id: 3,
    title: 'UGM Virtual Career Fair',
    organizer: 'Universitas Gadjah Mada',
    organizerSlug: 'ugm',
    date: '2024-09-20',
    time: '24 Jam Online',
    location: 'Online / Virtual',
    province: 'Online',
    city: 'Online',
    type: 'Virtual Job Fair',
    isFeatured: false,
    image: 'https://picsum.photos/seed/event3/800/450',
    description: 'Job fair virtual yang menghubungkan lulusan UGM dan umum dengan puluhan perusahaan nasional dan multinasional. Daftar online dan ikuti berbagai webinar karir gratis!',
    participatingCompanies: [
      { name: 'Unilever', logo: 'https://picsum.photos/80/40?random=6' },
      { name: 'Shopee', logo: 'https://picsum.photos/80/40?random=7', slug: 'shopee' },
      { name: 'BCG', logo: 'https://picsum.photos/80/40?random=8' },
    ],
    availablePositions: ['Future Leaders Program', 'Data Scientist', 'Business Analyst'],
  },
];

export const INITIAL_BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    image: 'https://picsum.photos/seed/blog1/400/300',
    category: 'Tips Karir',
    categoryColor: 'blue',
    title: '5 Kesalahan Umum dalam CV yang Bikin HRD Ilfeel',
    description: 'Hindari kesalahan-kesalahan sepele ini agar CV Anda lebih menonjol dan lolos seleksi administrasi.',
    posted: '1 hari yang lalu',
    content: `Membuat CV yang sempurna adalah langkah pertama yang krusial dalam mencari pekerjaan. Namun, banyak pencari kerja yang tanpa sadar melakukan kesalahan-kesalahan kecil yang bisa membuat rekruter langsung kehilangan minat. Berikut adalah 5 kesalahan umum yang harus Anda hindari:\n\n1. **Typo dan Kesalahan Tata Bahasa:** Ini adalah kesalahan paling fatal. CV yang penuh typo menunjukkan Anda tidak teliti dan kurang profesional. Selalu periksa ulang (proofread) CV Anda beberapa kali sebelum mengirimkannya.\n\n2. **Menggunakan Satu CV untuk Semua Lamaran:** Setiap posisi pekerjaan memiliki kualifikasi yang berbeda. Sesuaikan CV Anda dengan menyoroti pengalaman dan keahlian yang paling relevan dengan pekerjaan yang Anda lamar. Ini menunjukkan bahwa Anda serius dan benar-benar tertarik pada posisi tersebut.\n\n3. **Terlalu Panjang dan Bertele-tele:** Rekruter hanya memiliki waktu beberapa detik untuk memindai CV Anda. Buatlah CV yang ringkas, padat, dan jelas. Idealnya, CV tidak lebih dari 1-2 halaman. Gunakan bullet points untuk menjelaskan tugas dan pencapaian Anda.\n\n4. **Desain yang Terlalu Ramai atau Sulit Dibaca:** Meskipun kreativitas dihargai, CV bukanlah tempat untuk desain yang berlebihan (kecuali untuk industri kreatif). Gunakan font yang profesional dan mudah dibaca, serta layout yang bersih dan terstruktur.\n\n5. **Fokus pada Tugas, Bukan Pencapaian:** Jangan hanya menuliskan daftar tugas (job description) Anda di pekerjaan sebelumnya. Tunjukkan dampak dan pencapaian Anda. Gunakan angka dan data untuk mengkuantifikasi hasil kerja Anda. Contoh: "Meningkatkan penjualan sebesar 20% dalam 3 bulan" lebih baik daripada "Bertanggung jawab atas penjualan".\n\nDengan menghindari kesalahan-kesalahan ini, CV Anda akan terlihat lebih profesional dan memiliki peluang lebih besar untuk menarik perhatian HRD.`
  },
  {
    id: 2,
    image: 'https://picsum.photos/seed/blog2/400/300',
    category: 'Wawancara',
    categoryColor: 'green',
    title: 'Cara Menjawab Pertanyaan "Apa Kelemahan Terbesarmu?" Saat Wawancara',
    description: 'Ubah pertanyaan jebakan ini menjadi kesempatan untuk menunjukkan kesadaran diri dan kemauan untuk berkembang.',
    posted: '3 hari yang lalu',
    content: `Pertanyaan "Apa kelemahan terbesarmu?" adalah salah satu pertanyaan yang paling ditakuti oleh para pencari kerja. Namun, jika dijawab dengan strategi yang tepat, pertanyaan ini bisa menjadi momen untuk menunjukkan kualitas terbaik Anda. Kuncinya adalah jujur, tetapi tetap strategis.\n\n**Hindari Jawaban Klise:** Jangan pernah menjawab dengan kelemahan yang sebenarnya adalah kelebihan terselubung, seperti "Saya terlalu perfeksionis" atau "Saya seorang pekerja keras". Rekruter sudah bosan mendengar jawaban ini dan akan menganggap Anda tidak tulus.\n\n**Gunakan Rumus STAR (Situation, Task, Action, Result) yang Dimodifikasi:**\n1. **Sebutkan Kelemahan yang Nyata (tapi tidak fatal):** Pilih kelemahan yang jujur dan relevan, tetapi tidak akan menghalangi Anda untuk melakukan pekerjaan tersebut. Contohnya, kesulitan dalam berbicara di depan umum (public speaking) atau terlalu fokus pada detail sehingga kadang melupakan gambaran besar.\n\n2. **Tunjukkan Langkah-langkah Perbaikan:** Jelaskan tindakan konkret yang telah Anda lakukan untuk mengatasi kelemahan tersebut. Ini menunjukkan bahwa Anda proaktif dan memiliki kemauan untuk belajar dan berkembang.\n\n3. **Berikan Contoh Hasil Positif:** Ceritakan hasil positif dari usaha perbaikan Anda. Ini membuktikan bahwa Anda serius dalam pengembangan diri.\n\n**Contoh Jawaban yang Baik:**\n"Salah satu area yang sedang saya kembangkan adalah delegasi tugas. Dulu, saya cenderung ingin mengerjakan semuanya sendiri untuk memastikan hasilnya sempurna. Namun, saya sadar ini tidak efisien dan bisa memperlambat tim. Untuk mengatasinya, saya mulai mengikuti pelatihan manajemen proyek dan belajar mempercayai kemampuan rekan tim saya. Saya mulai dengan mendelegasikan tugas-tugas kecil dan memberikan panduan yang jelas. Hasilnya, proyek terakhir kami selesai lebih cepat dari tenggat waktu dan anggota tim saya merasa lebih diberdayakan."\n\nDengan jawaban seperti ini, Anda menunjukkan kesadaran diri, inisiatif, dan komitmen untuk menjadi lebih baik, yang semuanya adalah kualitas yang dicari oleh perusahaan.`
  },
  {
    id: 3,
    image: 'https://picsum.photos/seed/blog3/400/300',
    category: 'BUMN',
    categoryColor: 'blue',
    title: 'Panduan Lengkap Lolos Tes TKD dan Core Values BUMN 2024',
    description: 'Siapkan dirimu menghadapi seleksi BUMN dengan memahami materi dan tips mengerjakan Tes Kemampuan Dasar dan AKHLAK.',
    posted: '5 hari yang lalu',
    content: `Seleksi Bersama BUMN adalah salah satu rekrutmen yang paling dinanti setiap tahunnya. Dua tahap penting yang harus dilalui adalah Tes Kemampuan Dasar (TKD) dan Tes Core Values BUMN (AKHLAK). Berikut panduan untuk mempersiapkan diri Anda.\n\n**1. Tes Kemampuan Dasar (TKD)**\nTKD mirip dengan Tes Intelegensi Umum (TIU) pada seleksi CPNS. Tes ini mengukur kemampuan dasar Anda dan biasanya terdiri dari tiga bagian:\n\n*   **Tes Verbal:** Meliputi sinonim, antonim, analogi, dan pemahaman wacana. Perbanyak kosakata Anda dengan rajin membaca dan berlatih soal-soal.\n*   **Tes Numerik:** Terdiri dari aritmetika, deret angka, dan soal cerita matematika. Latih kembali kemampuan berhitung dasar Anda dan pelajari pola-pola deret yang sering muncul.\n*   **Tes Logika/Penalaran:** Menguji kemampuan berpikir logis Anda melalui soal penalaran logis (silogisme) dan penalaran analitis. Kunci utamanya adalah fokus dan memahami premis yang diberikan.\n\n**Tips Lolos TKD:**\n- **Manajemen Waktu:** Waktu pengerjaan sangat terbatas. Jangan terlalu lama terpaku pada satu soal yang sulit. Kerjakan soal yang Anda anggap mudah terlebih dahulu.\n- **Latihan Rutin:** Kunci utama adalah berlatih. Banyak buku dan platform online yang menyediakan simulasi soal TKD BUMN. Semakin sering berlatih, Anda akan semakin terbiasa dengan tipe soal dan manajemen waktu.\n\n**2. Tes Core Values BUMN (AKHLAK)**\nTes ini bertujuan untuk mengukur kesesuaian karakter Anda dengan nilai-nilai utama BUMN, yaitu **AKHLAK** (Amanah, Kompeten, Harmonis, Loyal, Adaptif, Kolaboratif).\n\n*   **Amanah:** Memegang teguh kepercayaan yang diberikan.\n*   **Kompeten:** Terus belajar dan mengembangkan kapabilitas.\n*   **Harmonis:** Saling peduli dan menghargai perbedaan.\n*   **Loyal:** Berdedikasi dan mengutamakan kepentingan Bangsa dan Negara.\n*   **Adaptif:** Terus berinovasi dan antusias dalam menggerakkan ataupun menghadapi perubahan.\n*   **Kolaboratif:** Membangun kerja sama yang sinergis.\n\n**Tips Lolos Tes AKHLAK:**\n- **Pahami Setiap Nilai:** Pelajari definisi dan contoh penerapan dari setiap nilai AKHLAK dalam konteks dunia kerja.\n- **Jadilah Diri Sendiri (yang Terbaik):** Soal biasanya berupa studi kasus atau pilihan ganda yang menggambarkan situasi kerja. Pilih jawaban yang paling mencerminkan diri Anda, namun tetap selaras dengan nilai-nilai AKHLAK. Tunjukkan bahwa Anda adalah individu yang positif, proaktif, dan dapat bekerja sama dalam tim.\n- **Konsisten:** Tes ini seringkali memiliki beberapa soal yang menguji nilai yang sama dengan cara berbeda. Pastikan jawaban Anda konsisten untuk menunjukkan bahwa Anda tidak berpura-pura.\n\nDengan persiapan yang matang, Anda dapat menghadapi kedua tes ini dengan lebih percaya diri. Selamat berjuang!`
  },
  {
    id: 4,
    image: 'https://picsum.photos/seed/blog4/400/300',
    category: 'Fresh Graduate',
    categoryColor: 'orange',
    title: 'Cara Membuat Portofolio yang Menarik bagi Fresh Graduate',
    description: 'Belum punya pengalaman kerja? Jangan khawatir! Portofolio bisa menjadi senjata ampuh untuk menunjukkan keahlianmu.',
    posted: '6 hari yang lalu'
  },
  {
    id: 5,
    image: 'https://picsum.photos/seed/blog5/400/300',
    category: 'Tips Karir',
    categoryColor: 'blue',
    title: 'Pentingnya Networking dalam Membangun Karir',
    description: 'Lebih dari sekadar kenalan, networking adalah tentang membangun hubungan yang saling menguntungkan. Simak caranya di sini!',
    posted: '1 minggu yang lalu'
  },
  {
    id: 6,
    image: 'https://picsum.photos/seed/blog6/400/300',
    category: 'Wawancara',
    categoryColor: 'green',
    title: 'Tanda-tanda Wawancara Kerjamu Berjalan dengan Sukses',
    description: 'Penasaran dengan hasil interview? Kenali tanda-tanda positif ini yang menunjukkan kamu berpeluang besar lolos.',
    posted: '1 minggu yang lalu'
  }
];

export const PARTNER_LOGOS = [
  'https://picsum.photos/150/60?random=20',
  'https://picsum.photos/150/60?random=21',
  'https://picsum.photos/150/60?random=22',
  'https://picsum.photos/150/60?random=23',
  'https://picsum.photos/150/60?random=24',
  'https://picsum.photos/150/60?random=25',
];


export const INITIAL_COMPANY_PROFILES: CompanyProfile[] = [
    { id: 1, name: 'PT Pertamina (Persero)', slug: 'pertamina', logo: 'https://picsum.photos/100/100?random=1', description: 'BUMN energi terkemuka di Indonesia, mengelola sektor hulu hingga hilir minyak dan gas.', type: 'BUMN', jobsAvailable: 0 },
    { id: 2, name: 'PT Bank Mandiri (Persero) Tbk', slug: 'bank-mandiri', logo: 'https://picsum.photos/100/100?random=2', description: 'Salah satu bank terbesar di Indonesia yang menyediakan berbagai layanan keuangan.', type: 'BUMN', jobsAvailable: 1 },
    { id: 3, name: 'PT Telkom Indonesia (Persero) Tbk', slug: 'telkom-indonesia', logo: 'https://picsum.photos/100/100?random=3', description: 'Perusahaan telekomunikasi terbesar di Indonesia dengan layanan yang mencakup seluler, internet, dan TV kabel.', type: 'BUMN', jobsAvailable: 1 },
    { id: 4, name: 'Gojek', slug: 'gojek', logo: 'https://picsum.photos/100/100?random=4', description: 'Platform on-demand terkemuka yang menyediakan layanan transportasi, logistik, dan pembayaran digital.', type: 'SWASTA', jobsAvailable: 1 },
    { id: 5, name: 'Shopee Indonesia', slug: 'shopee', logo: 'https://picsum.photos/100/100?random=5', description: 'Platform e-commerce terdepan di Asia Tenggara, menawarkan pengalaman belanja online yang mudah dan aman.', type: 'SWASTA', jobsAvailable: 0 },
    { id: 6, name: 'Kementerian Keuangan RI', slug: 'kemenkeu', logo: 'https://picsum.photos/100/100?random=6', description: 'Instansi pemerintah yang bertanggung jawab atas pengelolaan keuangan negara dan kebijakan fiskal.', type: 'INSTANSI', jobsAvailable: 0 },
    { id: 7, name: 'PT Waskita Karya (Persero)', slug: 'waskita-karya', logo: 'https://picsum.photos/100/100?random=13', description: 'BUMN konstruksi terkemuka yang telah menyelesaikan berbagai proyek infrastruktur berskala besar.', type: 'BUMN', jobsAvailable: 1},
    { id: 8, name: 'PT GS Battery', slug: 'gs-battery', logo: 'https://picsum.photos/100/100?random=12', description: 'Pelopor dalam produksi aki di Indonesia dan merupakan bagian dari Astra Otoparts Tbk.', type: 'SWASTA', jobsAvailable: 1},
    { id: 9, name: 'PT Japfa Comfeed Indonesia', slug: 'japfa-comfeed', logo: 'https://picsum.photos/100/100?random=11', description: 'Salah satu perusahaan agribisnis terbesar di Indonesia, meliputi pembuatan pakan ternak hingga pengolahan unggas.', type: 'SWASTA', jobsAvailable: 1},
    { id: 10, name: 'PT Dahana (Persero)', slug: 'pt-dahana', logo: 'https://picsum.photos/100/100?random=10', description: 'Badan Usaha Milik Negara (BUMN) yang bergerak di bidang industri bahan peledak.', type: 'BUMN', jobsAvailable: 1},
    { id: 11, name: 'SurveyMonkey', slug: 'surveymonkey', logo: 'https://picsum.photos/100/100?random=31', description: 'Platform survei online global yang membantu individu dan organisasi mengumpulkan wawasan.', type: 'SWASTA', jobsAvailable: 0 },
    { id: 12, name: 'TikTok', slug: 'tiktok', logo: 'https://picsum.photos/100/100?random=32', description: 'Platform video sosial terkemuka untuk membuat dan berbagi video pendek.', type: 'SWASTA', jobsAvailable: 0 },
    { id: 13, name: 'PT Maju Jaya Abadi', slug: 'pt-maju-jaya-abadi', logo: 'https://picsum.photos/100/100?random=50', description: 'Perusahaan swasta fiktif yang bergerak di bidang distribusi dan penjualan untuk keperluan acara rekrutmen.', type: 'SWASTA', jobsAvailable: 0 },
    { id: 14, name: 'Universitas Gadjah Mada', slug: 'ugm', logo: 'https://picsum.photos/100/100?random=51', description: 'Salah satu universitas negeri terkemuka di Indonesia, sering mengadakan acara karir.', type: 'INSTANSI', jobsAvailable: 0 }
];

export const INITIAL_MISI_CUAN_OFFERS: MisiCuanOffer[] = [
  {
    id: 1,
    company: 'Shopee',
    companySlug: 'shopee',
    logo: 'https://picsum.photos/80/80?random=5',
    title: 'Instal & Daftar Akun Baru',
    time: '5 Menit',
    expiryDate: '31 Des 2024',
    description: 'Dapatkan imbalan dengan mengunduh aplikasi Shopee dan mendaftarkan akun baru. Misi hanya berlaku untuk pengguna yang belum pernah memiliki akun Shopee sebelumnya.',
    quota: 1000,
    submissions: 200,
    reward: 'Saldo Koin Rp 10.000',
    details: 'Pastikan Anda menggunakan link unik yang kami sediakan untuk mengunduh aplikasi. Pendaftaran harus diselesaikan dalam waktu 24 jam setelah klik link. Imbalan akan diproses setelah verifikasi data.',
    steps: [
      'Klik tombol "Ambil Misi" untuk mendapatkan link unik.',
      'Unduh aplikasi Shopee melalui link tersebut.',
      'Buka aplikasi dan daftar akun baru menggunakan email atau nomor telepon.',
      'Verifikasi akun Anda.',
      'Ambil screenshot halaman profil akun baru Anda.'
    ],
    submissionRequirement: 'Unggah screenshot halaman profil akun baru Anda yang menunjukkan username dan tanggal bergabung.',
    submissionFields: [
      { id: 1, label: 'Username Akun Shopee', type: 'text' },
      { id: 2, label: 'Screenshot Halaman Profil', type: 'file' },
    ]
  },
  {
    id: 2,
    company: 'SurveyMonkey',
    companySlug: 'surveymonkey',
    logo: 'https://picsum.photos/80/80?random=31',
    title: 'Isi Survei Pasar',
    time: '15 Menit',
    expiryDate: '15 Agu 2024',
    description: 'Bantu kami memahami kebiasaan belanja online Anda dengan mengisi survei singkat ini. Jawaban Anda akan dirahasiakan dan digunakan untuk keperluan riset.',
    quota: 500,
    submissions: 275,
    reward: 'Voucher Pulsa Rp 25.000',
    details: 'Survei harus diisi dengan jujur dan lengkap. Jawaban yang tidak konsisten atau asal-asalan akan didiskualifikasi. Satu pengguna hanya dapat mengikuti satu kali.',
    steps: [
      'Klik tombol untuk memulai survei.',
      'Jawab semua pertanyaan yang diberikan.',
      'Pada halaman terakhir, Anda akan mendapatkan kode unik.',
      'Screenshot halaman yang berisi kode unik tersebut.'
    ],
    submissionRequirement: 'Unggah screenshot halaman terakhir survei yang menampilkan kode unik penyelesaian.',
     submissionFields: [
      { id: 1, label: 'Kode Unik Survei', type: 'text' },
      { id: 2, label: 'Screenshot Halaman Kode Unik', type: 'file' },
    ]
  },
  {
    id: 3,
    company: 'TikTok',
    companySlug: 'tiktok',
    logo: 'https://picsum.photos/80/80?random=32',
    title: 'Tonton Video & Beri Like',
    time: '10 Menit',
    expiryDate: '30 Sep 2024',
    description: 'Tonton 5 video dari kreator yang kami tunjuk dan berikan "like" pada setiap video. Misi mudah untuk mengisi waktu luangmu!',
    quota: 2000,
    submissions: 1700,
    reward: 'Saldo GoPay Rp 5.000',
    details: 'Pastikan Anda menonton setiap video setidaknya selama 15 detik sebelum memberikan "like". Akun TikTok Anda harus aktif dan bukan akun baru.',
    steps: [
      'Buka daftar link video yang kami sediakan.',
      'Tonton video pertama selama minimal 15 detik, lalu berikan like.',
      'Ulangi untuk 4 video lainnya.',
      'Ambil screenshot riwayat tontonan atau aktivitas "like" Anda yang menunjukkan 5 video tersebut.'
    ],
    submissionRequirement: 'Unggah screenshot dari halaman aktivitas Anda yang menunjukkan bahwa Anda telah menyukai 5 video yang ditentukan.',
     submissionFields: [
      { id: 1, label: 'Link ke Profil TikTok Anda', type: 'url' },
      { id: 2, label: 'Screenshot Aktivitas "Like"', type: 'file' },
    ]
  },
];

export const INITIAL_MISI_SUBMISSIONS: MisiSubmission[] = [
    {
        id: 1,
        misiId: 1,
        misiTitle: 'Instal & Daftar Akun Baru',
        user: 'Pengguna #2819',
        submissionDate: '20 Jul 2024',
        status: 'Pending',
        data: [
            { fieldId: 1, label: 'Username Akun Shopee', value: 'pengguna_baru_123' },
            { fieldId: 2, label: 'Screenshot Halaman Profil', value: { fileName: 'ss-shopee.jpg', url: '#' } }
        ]
    },
    {
        id: 2,
        misiId: 2,
        misiTitle: 'Isi Survei Pasar',
        user: 'Pengguna #7462',
        submissionDate: '19 Jul 2024',
        status: 'Approved',
        data: [
            { fieldId: 1, label: 'Kode Unik Survei', value: 'SM-XYZ-987' },
            { fieldId: 2, label: 'Screenshot Halaman Kode Unik', value: { fileName: 'bukti-survei.png', url: '#' } }
        ]
    },
     {
        id: 3,
        misiId: 1,
        misiTitle: 'Instal & Daftar Akun Baru',
        user: 'Pengguna #5511',
        submissionDate: '18 Jul 2024',
        status: 'Rejected',
        data: [
            { fieldId: 1, label: 'Username Akun Shopee', value: 'akun_lama_01' },
            { fieldId: 2, label: 'Screenshot Halaman Profil', value: { fileName: 'screenshot.jpg', url: '#' } }
        ]
    },
];

export const INITIAL_PELATIHAN_INFO: PelatihanInfo[] = [
  {
    id: 1,
    image: 'https://picsum.photos/seed/pelatihan1/400/300',
    category: 'Sertifikasi',
    title: 'Pelatihan dan Sertifikasi Ahli K3 Umum',
    organizer: 'Kementerian Ketenagakerjaan RI',
    date: '15 Agu 2024 - 28 Agu 2024',
    location: 'Online',
    description: 'Program resmi untuk mendapatkan sertifikasi Ahli Keselamatan dan Kesehatan Kerja (K3) Umum dari Kemnaker RI. Pelajari regulasi, identifikasi bahaya, dan implementasi sistem manajemen K3.',
    fullDescription: '<p>Program resmi untuk mendapatkan sertifikasi <b>Ahli Keselamatan dan Kesehatan Kerja (K3) Umum</b> dari Kemnaker RI. Pelatihan ini dirancang untuk mencetak tenaga ahli K3 yang kompeten, profesional, dan mampu mengimplementasikan sistem manajemen K3 di tempat kerja sesuai dengan peraturan perundang-undangan yang berlaku.</p><h3>Materi yang akan dipelajari:</h3><ul><li>Dasar-dasar K3 dan regulasi terkait.</li><li>Identifikasi, penilaian, dan pengendalian risiko bahaya.</li><li>Sistem Manajemen K3 (SMK3).</li><li>Manajemen keadaan darurat.</li><li>Investigasi kecelakaan kerja.</li></ul><p>Lulusan pelatihan akan mendapatkan sertifikat dan surat keputusan penunjukan (SKP) sebagai Ahli K3 Umum dari Kemnaker RI.</p>',
    registrationLink: '#',
    videoEmbedUrl: 'https://www.youtube.com/embed/g_2Q6a_f-4g',
    pdfEmbedUrl: 'https://drive.google.com/file/d/1s_h_Od3Al945-P8i2e3a-m2K3k2lJk3F/preview',
  },
  {
    id: 2,
    image: 'https://picsum.photos/seed/pelatihan2/400/300',
    category: 'Bahasa Asing',
    title: 'TOEFL iBT Preparation Class',
    organizer: 'Lembaga Bahasa Internasional',
    date: 'Setiap Senin & Rabu',
    location: 'Jakarta & Online',
    description: 'Kelas persiapan intensif untuk menghadapi tes TOEFL iBT. Tingkatkan skor Anda dengan strategi pengerjaan soal, latihan, dan simulasi tes dari pengajar berpengalaman.',
    registrationLink: '#',
  },
  {
    id: 3,
    image: 'https://picsum.photos/seed/pelatihan3/400/300',
    category: 'Data & Analitik',
    title: 'Bootcamp Data Science with Python',
    organizer: 'Tech Academy',
    date: 'Batch September 2024',
    location: 'Online',
    description: 'Pelajari dasar-dasar data science, mulai dari Python, SQL, statistik, hingga machine learning. Program intensif selama 12 minggu dengan jaminan penyaluran kerja.',
    registrationLink: '#',
  },
  {
    id: 4,
    image: 'https://picsum.photos/seed/pelatihan4/400/300',
    category: 'Keuangan',
    title: 'Brevet Pajak A & B Terpadu',
    organizer: 'Ikatan Akuntan Indonesia (IAI)',
    date: 'Batch Oktober 2024',
    location: 'Bandung',
    description: 'Kuasai peraturan perpajakan terbaru di Indonesia untuk perorangan (Brevet A) dan badan/perusahaan (Brevet B). Cocok untuk mahasiswa dan profesional di bidang akuntansi dan keuangan.',
    registrationLink: '#',
  },
  {
    id: 5,
    image: 'https://picsum.photos/seed/pelatihan5/400/300',
    category: 'Manajemen Proyek',
    title: 'Project Management Professional (PMP) Certification Prep',
    organizer: 'Project Management Institute (PMI) Indonesia',
    date: '20 Sep 2024 - 22 Sep 2024',
    location: 'Surabaya',
    description: 'Kursus persiapan untuk ujian sertifikasi PMP global. Pelajari kerangka kerja PMBOK, manajemen risiko, agile, dan praktik terbaik manajemen proyek.',
    registrationLink: '#',
  },
  {
    id: 6,
    image: 'https://picsum.photos/seed/pelatihan6/400/300',
    category: 'Digital Marketing',
    title: 'Certified Digital Marketer (CDM)',
    organizer: 'Digital Marketing Institute',
    date: 'Self-paced',
    location: 'Online',
    description: 'Program sertifikasi internasional yang mencakup semua aspek digital marketing, dari SEO, SEM, social media marketing, hingga email marketing dan analitik.',
    registrationLink: '#',
  },
];

export const INITIAL_MAJORS: Major[] = [
  { id: 1, name: 'Administrasi Perkantoran' },
  { id: 2, name: 'Manajemen' },
  { id: 3, name: 'Ilmu Komunikasi' },
  { id: 4, name: 'Sekretaris' },
  { id: 5, name: 'Semua Jurusan' },
  { id: 6, name: 'Teknik Industri' },
  { id: 7, name: 'Teknik Mesin' },
  { id: 8, name: 'Teknologi Pangan' },
  { id: 9, name: 'Teknik Kimia' },
  { id: 10, name: 'Teknik Elektro' },
  { id: 11, name: 'Mekatronika' },
  { id: 12, name: 'Teknik Listrik' },
  { id: 13, name: 'Akuntansi' },
  { id: 14, name: 'Manajemen Keuangan' },
  { id: 15, name: 'Perpajakan' },
  { id: 16, name: 'Marketing' },
  { id: 17, name: 'Manajemen Bisnis' },
  { id: 18, name: 'DKV' },
  { id: 19, name: 'Sistem Informasi' },
  { id: 20, name: 'Ekonomi' },
  { id: 21, name: 'Perbankan' },
  { id: 22, name: 'Statistika' },
];

const allInitialTags = INITIAL_JOBS.flatMap(job => job.tags);
const uniqueInitialTags = [...new Set(allInitialTags)];

export const INITIAL_TAGS: Tag[] = uniqueInitialTags.map((tag, index) => ({
    id: index + 1,
    name: tag
}));

export const INITIAL_ADMIN_USERS: AdminUser[] = [
    { id: 1, name: 'Super Admin', email: 'admin@kabarkarir.com', role: 'Super Admin' },
    { id: 2, name: 'Content Manager', email: 'content@kabarkarir.com', role: 'Content Manager' },
];


// Data Provinsi dan Kota
export const PROVINCES: { [key: string]: string } = {
  "11": "ACEH",
  "12": "SUMATERA UTARA",
  "13": "SUMATERA BARAT",
  "14": "RIAU",
  "15": "JAMBI",
  "16": "SUMATERA SELATAN",
  "17": "BENGKULU",
  "18": "LAMPUNG",
  "19": "KEPULAUAN BANGKA BELITUNG",
  "21": "KEPULAUAN RIAU",
  "31": "DKI JAKARTA",
  "32": "JAWA BARAT",
  "33": "JAWA TENGAH",
  "34": "DAERAH ISTIMEWA YOGYAKARTA",
  "35": "JAWA TIMUR",
  "36": "BANTEN",
  "51": "BALI",
  "52": "NUSA TENGGARA BARAT",
  "53": "NUSA TENGGARA TIMUR",
  "61": "KALIMANTAN BARAT",
  "62": "KALIMANTAN TENGAH",
  "63": "KALIMANTAN SELATAN",
  "64": "KALIMANTAN TIMUR",
  "65": "KALIMANTAN UTARA",
  "71": "SULAWESI UTARA",
  "72": "SULAWESI TENGAH",
  "73": "SULAWESI SELATAN",
  "74": "SULAWESI TENGGARA",
  "75": "GORONTALO",
  "76": "SULAWESI BARAT",
  "81": "MALUKU",
  "82": "MALUKU UTARA",
  "91": "PAPUA BARAT",
  "94": "PAPUA"
};

export const CITIES_BY_PROVINCE = {
  "11": {
    "1101": "KAB. ACEH SELATAN",
    "1102": "KAB. ACEH TENGGARA",
    "1103": "KAB. ACEH TIMUR",
    "1104": "KAB. ACEH TENGAH",
    "1105": "KAB. ACEH BARAT",
    "1106": "KAB. ACEH BESAR",
    "1107": "KAB. PIDIE",
    "1108": "KAB. ACEH UTARA",
    "1109": "KAB. SIMEULUE",
    "1110": "KAB. ACEH SINGKIL",
    "1111": "KAB. BIREUEN",
    "1112": "KAB. ACEH BARAT DAYA",
    "1113": "KAB. GAYO LUES",
    "1114": "KAB. ACEH JAYA",
    "1115": "KAB. NAGAN RAYA",
    "1116": "KAB. ACEH TAMIANG",
    "1117": "KAB. BENER MERIAH",
    "1118": "KAB. PIDIE JAYA",
    "1171": "KOTA BANDA ACEH",
    "1172": "KOTA SABANG",
    "1173": "KOTA LHOKSEUMAWE",
    "1174": "KOTA LANGSA",
    "1175": "KOTA SUBULUSSALAM"
  },
  "12": {
    "1201": "KAB. TAPANULI TENGAH",
    "1202": "KAB. TAPANULI UTARA",
    "1203": "KAB. TAPANULI SELATAN",
    "1204": "KAB. NIAS",
    "1205": "KAB. LANGKAT",
    "1206": "KAB. KARO",
    "1207": "KAB. DELI SERDANG",
    "1208": "KAB. SIMALUNGUN",
    "1209": "KAB. ASAHAN",
    "1210": "KAB. LABUHANBATU",
    "1211": "KAB. DAIRI",
    "1212": "KAB. TOBA SAMOSIR",
    "1213": "KAB. MANDAILING NATAL",
    "1214": "KAB. NIAS SELATAN",
    "1215": "KAB. PAKPAK BHARAT",
    "1216": "KAB. HUMBANG HASUNDUTAN",
    "1217": "KAB. SAMOSIR",
    "1218": "KAB. SERDANG BEDAGAI",
    "1219": "KAB. BATU BARA",
    "1220": "KAB. PADANG LAWAS UTARA",
    "1221": "KAB. PADANG LAWAS",
    "1222": "KAB. LABUHANBATU SELATAN",
    "1223": "KAB. LABUHANBATU UTARA",
    "1224": "KAB. NIAS UTARA",
    "1225": "KAB. NIAS BARAT",
    "1271": "KOTA MEDAN",
    "1272": "KOTA PEMATANGSIANTAR",
    "1273": "KOTA SIBOLGA",
    "1274": "KOTA TANJUNG BALAI",
    "1275": "KOTA BINJAI",
    "1276": "KOTA TEBING TINGGI",
    "1277": "KOTA PADANGSIDIMPUAN",
    "1278": "KOTA GUNUNGSITOLI"
  },
  "31": {
    "3101": "KAB. ADM. KEP. SERIBU",
    "3171": "KOTA ADM. JAKARTA PUSAT",
    "3172": "KOTA ADM. JAKARTA UTARA",
    "3173": "KOTA ADM. JAKARTA BARAT",
    "3174": "KOTA ADM. JAKARTA SELATAN",
    "3175": "KOTA ADM. JAKARTA TIMUR"
  },
  "32": {
    "3201": "KAB. BOGOR",
    "3202": "KAB. SUKABUMI",
    "3203": "KAB. CIANJUR",
    "3204": "KAB. BANDUNG",
    "3205": "KAB. GARUT",
    "3206": "KAB. TASIKMALAYA",
    "3207": "KAB. CIAMIS",
    "3208": "KAB. KUNINGAN",
    "3209": "KAB. CIREBON",
    "3210": "KAB. MAJALENGKA",
    "3211": "KAB. SUMEDANG",
    "3212": "KAB. INDRAMAYU",
    "3213": "KAB. SUBANG",
    "3214": "KAB. PURWAKARTA",
    "3215": "KAB. KARAWANG",
    "3216": "KAB. BEKASI",
    "3217": "KAB. BANDUNG BARAT",
    "3218": "KAB. PANGANDARAN",
    "3271": "KOTA BOGOR",
    "3272": "KOTA SUKABUMI",
    "3273": "KOTA BANDUNG",
    "3274": "KOTA CIREBON",
    "3275": "KOTA BEKASI",
    "3276": "KOTA DEPOK",
    "3277": "KOTA CIMAHI",
    "3278": "KOTA TASIKMALAYA",
    "3279": "KOTA BANJAR"
  },
  "34": {
    "3401": "KAB. KULON PROGO",
    "3402": "KAB. BANTUL",
    "3403": "KAB. GUNUNGKIDUL",
    "3404": "KAB. SLEMAN",
    "3471": "KOTA YOGYAKARTA"
  },
  "35": {
    "3501": "KAB. PACITAN",
    "3502": "KAB. PONOROGO",
    "3503": "KAB. TRENGGALEK",
    "3504": "KAB. TULUNGAGUNG",
    "3505": "KAB. BLITAR",
    "3506": "KAB. KEDIRI",
    "3507": "KAB. MALANG",
    "3508": "KAB. LUMAJANG",
    "3509": "KAB. JEMBER",
    "3510": "KAB. BANYUWANGI",
    "3511": "KAB. BONDOWOSO",
    "3512": "KAB. SITUBONDO",
    "3513": "KAB. PROBOLINGGO",
    "3514": "KAB. PASURUAN",
    "3515": "KAB. SIDOARJO",
    "3516": "KAB. MOJOKERTO",
    "3517": "KAB. JOMBANG",
    "3518": "KAB. NGANJUK",
    "3519": "KAB. MADIUN",
    "3520": "KAB. MAGETAN",
    "3521": "KAB. NGAWI",
    "3522": "KAB. BOJONEGORO",
    "3523": "KAB. TUBAN",
    "3524": "KAB. LAMONGAN",
    "3525": "KAB. GRESIK",
    "3526": "KAB. BANGKALAN",
    "3527": "KAB. SAMPANG",
    "3528": "KAB. PAMEKASAN",
    "3529": "KAB. SUMENEP",
    "3571": "KOTA KEDIRI",
    "3572": "KOTA BLITAR",
    "3573": "KOTA MALANG",
    "3574": "KOTA PROBOLINGGO",
    "3575": "KOTA PASURUAN",
    "3576": "KOTA MOJOKERTO",
    "3577": "KOTA MADIUN",
    "3578": "KOTA SURABAYA",
    "3579": "KOTA BATU"
  }
  // Data provinsi dan kota lainnya akan mengikuti pola yang sama
};