-- ================================================
-- DUMMY DATA FOR KABARKARIR.COM
-- ================================================
-- This file contains dummy/sample data for development
-- Can be restored anytime by running this SQL file
-- ================================================

-- ===========================================
-- 1. FRONTEND-USER DATA (Jobs & Companies)
-- ===========================================

-- Companies Data
INSERT INTO
    companies (
        id,
        slug,
        name,
        logo,
        type,
        description,
        website
    )
VALUES (
        1,
        'pertamina',
        'PT Pertamina (Persero)',
        'https://via.placeholder.com/100?text=Pertamina',
        'BUMN',
        'BUMN yang bergerak di bidang energi meliputi minyak, gas serta energi baru dan terbarukan. Didirikan tahun 1957 dengan 30.000+ karyawan.',
        'https://www.pertamina.com'
    ),
    (
        2,
        'telkom',
        'PT Telkom Indonesia',
        'https://via.placeholder.com/100?text=Telkom',
        'BUMN',
        'BUMN terbesar di bidang telekomunikasi dan jaringan di Indonesia. Didirikan tahun 1965 dengan 20.000+ karyawan di Bandung.',
        'https://www.telkom.co.id'
    ),
    (
        3,
        'bni',
        'PT Bank Negara Indonesia (BNI)',
        'https://via.placeholder.com/100?text=BNI',
        'BUMN',
        'Bank BUMN terkemuka yang melayani nasabah korporasi dan retail. Didirikan tahun 1946 dengan 25.000+ karyawan.',
        'https://www.bni.co.id'
    ),
    (
        4,
        'pln',
        'PT PLN (Persero)',
        'https://via.placeholder.com/100?text=PLN',
        'BUMN',
        'BUMN yang mengelola penyediaan tenaga listrik di Indonesia. Didirikan tahun 1945 dengan 50.000+ karyawan.',
        'https://www.pln.co.id'
    ),
    (
        5,
        'tokopedia',
        'PT Tokopedia',
        'https://via.placeholder.com/100?text=Tokopedia',
        'SWASTA',
        'Platform e-commerce terbesar di Indonesia dengan jutaan merchant. Didirikan tahun 2009 dengan 5.000+ karyawan.',
        'https://www.tokopedia.com'
    ),
    (
        6,
        'gojek',
        'PT GoTo Gojek Tokopedia',
        'https://via.placeholder.com/100?text=Gojek',
        'SWASTA',
        'Super app yang menyediakan layanan transportasi, pengiriman, dan pembayaran digital. Didirikan tahun 2010 dengan 3.000+ karyawan.',
        'https://www.gojek.com'
    ),
    (
        7,
        'bukalapak',
        'PT Bukalapak',
        'https://via.placeholder.com/100?text=Bukalapak',
        'SWASTA',
        'Marketplace yang memberdayakan UMKM di seluruh Indonesia. Didirikan tahun 2010 dengan 2.000+ karyawan.',
        'https://www.bukalapak.com'
    ),
    (
        8,
        'mandiri',
        'PT Bank Mandiri (Persero)',
        'https://via.placeholder.com/100?text=Mandiri',
        'BUMN',
        'Bank terbesar di Indonesia dengan aset mencapai ratusan triliun rupiah. Didirikan tahun 1998 dengan 40.000+ karyawan.',
        'https://www.bankmandiri.co.id'
    ),
    (
        9,
        'bri',
        'PT Bank Rakyat Indonesia (BRI)',
        'https://via.placeholder.com/100?text=BRI',
        'BUMN',
        'Bank dengan jaringan terluas di Indonesia, fokus pada sektor mikro dan UMKM. Didirikan tahun 1895 dengan 80.000+ karyawan.',
        'https://www.bri.co.id'
    ),
    (
        10,
        'unilever',
        'PT Unilever Indonesia',
        'https://via.placeholder.com/100?text=Unilever',
        'SWASTA',
        'Perusahaan multinasional yang memproduksi produk consumer goods ternama. Didirikan tahun 1933 dengan 6.000+ karyawan.',
        'https://www.unilever.co.id'
    ) ON CONFLICT (id) DO NOTHING;

-- Jobs Data (Note: Using snake_case for database columns)
INSERT INTO
    jobs (
        id,
        company_slug,
        title,
        slug,
        company,
        logo,
        location,
        province,
        city,
        type,
        category,
        category_color,
        education,
        experience,
        salary_range,
        description,
        qualifications,
        benefits,
        how_to_apply,
        about_company,
        posted,
        due_date,
        is_active,
        tags,
        created_at,
        updated_at
    )
VALUES (
        1,
        'pertamina',
        'Management Trainee Program 2024',
        'management-trainee-pertamina-2024',
        'PT Pertamina (Persero)',
        'https://via.placeholder.com/100?text=Pertamina',
        'Jakarta, Indonesia',
        'DKI Jakarta',
        'Jakarta',
        'Full Time',
        'MT/ODP',
        'blue',
        'Strata 1',
        'Fresh Graduate',
        'Rp 8.000.000 - Rp 12.000.000',
        'Program pengembangan talenta muda untuk menjadi pemimpin masa depan Pertamina. Peserta akan mendapat pelatihan intensif dan rotasi divisi selama 1 tahun.',
        '["Lulusan S1/S2 dari universitas terkemuka", "IPK minimal 3.00", "Usia maksimal 27 tahun", "Mampu berbahasa Inggris aktif", "Belum menikah"]',
        '["Gaji kompetitif", "Asuransi kesehatan", "Jenjang karir jelas", "Pelatihan intensif", "Tunjangan perumahan"]',
        'Kirim lamaran melalui website resmi Pertamina careers',
        'BUMN terbesar di Indonesia yang bergerak di bidang energi',
        '2 minggu yang lalu',
        '2024-03-01',
        true,
        '["MT", "BUMN", "Fresh Graduate", "Management"]',
        NOW(),
        NOW()
    ),
    (
        2,
        'telkom',
        'IT Developer - Fresh Graduate Program',
        'it-developer-telkom-fresh-graduate',
        'Bandung, Jakarta',
        'Full-time',
        'Fresh Grad',
        'Strata 1',
        6000000,
        8000000,
        'Bergabung dengan tim IT Telkom untuk mengembangkan aplikasi dan sistem digital perusahaan. Program khusus untuk fresh graduate yang passionate di bidang teknologi.',
        '["Lulusan S1 Teknik Informatika/Sistem Informasi", "IPK minimal 3.25", "Menguasai Java, Python, atau JavaScript", "Fresh graduate atau pengalaman maksimal 1 tahun", "Memahami konsep database dan API"]',
        '["Gaji pokok + tunjangan", "Asuransi kesehatan keluarga", "Training & sertifikasi", "Work from anywhere", "Bonus tahunan"]',
        'Apply melalui portal rekrutmen Telkom Indonesia',
        '2024-02-01',
        '2024-03-15',
        true,
        890,
        NOW(),
        NOW()
    ),
    (
        3,
        'bni',
        'Credit Analyst Officer',
        'credit-analyst-bni',
        'Jakarta, Surabaya, Medan',
        'Full-time',
        'BUMN',
        'Strata 1',
        7000000,
        10000000,
        'Menganalisis kelayakan kredit nasabah korporasi dan retail. Posisi strategis di divisi Risk Management BNI dengan peluang karir yang cemerlang.',
        '["S1 Ekonomi/Manajemen/Akuntansi", "IPK minimal 3.00", "Memahami analisa laporan keuangan", "Detail oriented dan analytical thinking", "Bersedia ditempatkan di seluruh Indonesia"]',
        '["Gaji sesuai standar BUMN", "Bonus kinerja", "Asuransi kesehatan + jiwa", "Dana pensiun", "Cuti tahunan 12 hari"]',
        'Daftar melalui https://recruitment.bni.co.id',
        '2024-01-20',
        '2024-02-28',
        true,
        650,
        NOW(),
        NOW()
    ),
    (
        4,
        'tokopedia',
        'Product Manager Intern',
        'product-manager-intern-tokopedia',
        'Jakarta (WFO/Hybrid)',
        'Internship',
        'Intern',
        'Strata 1',
        4000000,
        5000000,
        'Kesempatan magang 6 bulan sebagai Product Manager di salah satu startup unicorn Indonesia. Belajar langsung dari PM senior dan terlibat dalam pengembangan produk.',
        '["Mahasiswa aktif S1 semester 6-8 atau fresh graduate", "Tertarik dengan product management", "Analytical dan problem solving skills", "Familiar dengan tools product management", "Dapat bekerja full-time selama 6 bulan"]',
        '["Uang saku kompetitif", "Sertifikat magang", "Mentoring dari PM senior", "Laptop & peralatan kerja", "Networking dengan tech community"]',
        'Submit portfolio dan CV ke careers@tokopedia.com',
        '2024-02-10',
        '2024-03-20',
        true,
        1450,
        NOW(),
        NOW()
    ),
    (
        5,
        'gojek',
        'Data Scientist',
        'data-scientist-gojek',
        'Jakarta',
        'Full-time',
        'Fresh Grad',
        'Strata 1',
        9000000,
        13000000,
        'Bergabung dengan data science team untuk menganalisis dan mengoptimalkan algoritma aplikasi Gojek. Bekerja dengan big data dan machine learning.',
        '["S1/S2 Matematika, Statistika, Computer Science", "IPK minimal 3.50", "Menguasai Python, R, SQL", "Pengalaman dengan ML frameworks (TensorFlow, PyTorch)", "Portfolio project data science"]',
        '["Salary package menarik", "Stock options", "Unlimited leave", "Flexible working hours", "Health & wellness program"]',
        'Apply via Gojek careers portal',
        '2024-01-25',
        '2024-03-10',
        true,
        2100,
        NOW(),
        NOW()
    ),
    (
        6,
        'pln',
        'Junior Engineer - Electrical',
        'junior-engineer-electrical-pln',
        'Jakarta, Surabaya, Makassar',
        'Full-time',
        'BUMN',
        'Strata 1',
        6500000,
        9000000,
        'Posisi engineer untuk maintenance dan pengembangan infrastruktur kelistrikan PLN. Program pengembangan kompetensi teknis yang terstruktur.',
        '["S1 Teknik Elektro", "IPK minimal 3.00", "Memahami sistem kelistrikan dan power plant", "Bersedia bekerja shift dan dinas luar", "Sehat jasmani dan rohani"]',
        '["Gaji + tunjangan kinerja", "Asuransi BPJS + swasta", "Rumah dinas (sesuai lokasi)", "Beasiswa S2", "Pensiun dijamin"]',
        'Pendaftaran melalui rekrutmen-pln.co.id',
        '2024-02-05',
        '2024-03-25',
        true,
        780,
        NOW(),
        NOW()
    ),
    (
        7,
        'mandiri',
        'Digital Banking Officer',
        'digital-banking-officer-mandiri',
        'Jakarta',
        'Full-time',
        'BUMN',
        'Strata 1',
        7500000,
        11000000,
        'Mengembangkan dan mengelola produk digital banking Bank Mandiri. Terlibat dalam transformasi digital perbankan Indonesia.',
        '["S1 semua jurusan (diutamakan IT/Perbankan)", "IPK minimal 3.25", "Memahami digital banking & fintech", "Customer oriented", "Komunikatif dan inovatif"]',
        '["Gaji kompetitif", "Bonus performance", "BPJS & asuransi swasta", "Career path jelas", "Learning & development program"]',
        'Kirim lamaran ke hrd@bankmandiri.co.id',
        '2024-01-18',
        '2024-03-05',
        true,
        920,
        NOW(),
        NOW()
    ),
    (
        8,
        'bukalapak',
        'Frontend Engineer',
        'frontend-engineer-bukalapak',
        'Jakarta (Remote-friendly)',
        'Full-time',
        'Fresh Grad',
        'Strata 1',
        7000000,
        10000000,
        'Develop dan maintain web platform Bukalapak menggunakan modern tech stack. Kesempatan bekerja dengan senior engineers dan learn best practices.',
        '["S1 Teknik Informatika atau sejenisnya", "Menguasai React.js, Next.js, TypeScript", "Paham state management (Redux/Zustand)", "Fresh graduate atau pengalaman 1-2 tahun", "Portfolio website/project"]',
        '["Competitive salary", "Remote work option", "Latest tech gadgets", "Annual bonus", "Medical insurance"]',
        'Apply through LinkedIn or Bukalapak careers page',
        '2024-02-08',
        '2024-03-18',
        true,
        1320,
        NOW(),
        NOW()
    ),
    (
        9,
        'bri',
        'Account Officer - Micro Banking',
        'account-officer-micro-bri',
        'Seluruh Indonesia',
        'Full-time',
        'BUMN',
        'Diploma 3',
        5500000,
        7500000,
        'Melayani nasabah segment mikro dan UMKM. Membantu pengembangan bisnis nasabah dan mencapai target penjualan produk BRI.',
        '["D3/S1 semua jurusan", "IPK minimal 2.75", "Komunikatif dan persuasif", "Menyukai pekerjaan lapangan", "Bersedia penempatan seluruh Indonesia"]',
        '["Gaji pokok + insentif", "Tunjangan transportasi", "Asuransi kesehatan", "Bonus pencapaian target", "Jenjang karir hingga manajer"]',
        'Daftar online di www.bri.co.id/karir',
        '2024-01-22',
        '2024-03-12',
        true,
        580,
        NOW(),
        NOW()
    ),
    (
        10,
        'unilever',
        'Supply Chain Management Trainee',
        'supply-chain-management-trainee-unilever',
        'Cikarang, Jakarta',
        'Full-time',
        'MT/ODP',
        'Strata 1',
        8500000,
        11500000,
        'Program 2 tahun untuk develop future supply chain leaders. Rotasi ke berbagai fungsi: procurement, production planning, logistics, dan distribution.',
        '["S1/S2 Teknik Industri/Manajemen", "IPK minimal 3.25", "Leadership potential", "English proficiency", "Analytical mindset"]',
        '["Attractive salary package", "International exposure", "Fast track career", "Comprehensive training", "Relocation support"]',
        'Submit application via Unilever careers website',
        '2024-02-12',
        '2024-03-30',
        true,
        1680,
        NOW(),
        NOW()
    ) ON CONFLICT (id) DO NOTHING;

-- Blog Posts
INSERT INTO
    blog_posts (
        id,
        slug,
        title,
        excerpt,
        content,
        author_name,
        category,
        featured_image,
        tags,
        is_published,
        posted_date,
        view_count,
        created_at,
        updated_at
    )
VALUES (
        1,
        'tips-lolos-interview-bumn',
        '10 Tips Sukses Interview BUMN 2024',
        'Panduan lengkap persiapan interview di perusahaan BUMN dari tahap screening hingga final interview.',
        '<h2>Persiapan Interview BUMN</h2><p>Interview di perusahaan BUMN memiliki karakteristik tersendiri. Berikut tips yang perlu Anda perhatikan...</p><h3>1. Pahami Profil Perusahaan</h3><p>Pelajari visi, misi, dan nilai-nilai perusahaan...</p>',
        'Admin KabarKarir',
        'Tips Karir',
        'https://via.placeholder.com/800x450?text=Interview+Tips',
        '["interview", "BUMN", "tips karir"]',
        true,
        '2024-02-15',
        3500,
        NOW(),
        NOW()
    ),
    (
        2,
        'cara-buat-cv-menarik-hrd',
        'Cara Membuat CV yang Menarik untuk HRD',
        'CV yang baik adalah kunci pertama membuka peluang karir. Pelajari struktur dan tips membuat CV yang eye-catching.',
        '<h2>Struktur CV yang Efektif</h2><p>CV yang baik harus memiliki struktur yang jelas dan informasi yang relevan...</p>',
        'Tim Redaksi',
        'Tips Karir',
        'https://via.placeholder.com/800x450?text=CV+Tips',
        '["CV", "resume", "tips karir"]',
        true,
        '2024-02-10',
        4200,
        NOW(),
        NOW()
    ),
    (
        3,
        'panduan-tes-psikotes-lengkap',
        'Panduan Lengkap Menghadapi Tes Psikotes',
        'Tes psikotes adalah tahapan penting dalam rekrutmen. Kenali jenis-jenis tes dan strategi mengerjakannya.',
        '<h2>Jenis-Jenis Tes Psikotes</h2><p>Ada berbagai jenis psikotes yang umum digunakan perusahaan...</p>',
        'Dr. Psikologi',
        'Tips Karir',
        'https://via.placeholder.com/800x450?text=Psikotes',
        '["psikotes", "tes", "rekrutmen"]',
        true,
        '2024-02-08',
        2890,
        NOW(),
        NOW()
    ) ON CONFLICT (id) DO NOTHING;

-- ===========================================
-- 2. FRONTEND-MAHASISWA DATA
-- ===========================================

-- Internships (Magang)
INSERT INTO
    internships (
        id,
        slug,
        title,
        company_name,
        company_logo,
        location,
        duration,
        stipend_min,
        stipend_max,
        description,
        requirements,
        benefits,
        application_url,
        start_date,
        end_date,
        is_active,
        view_count,
        created_at,
        updated_at
    )
VALUES (
        1,
        'magang-frontend-developer-tokopedia',
        'Frontend Developer Intern',
        'Tokopedia',
        'https://via.placeholder.com/80?text=Tokopedia',
        'Jakarta',
        '6 Bulan',
        3000000,
        4000000,
        'Kesempatan magang sebagai Frontend Developer di Tokopedia. Belajar dan mengembangkan fitur web menggunakan React dan TypeScript.',
        '["Mahasiswa aktif semester 5-8", "Menguasai HTML, CSS, JavaScript", "Familiar dengan React.js", "Dapat bekerja full-time 5 hari/minggu", "Portofolio project (GitHub)"]',
        '["Uang saku bulanan", "Sertifikat magang", "Mentoring dari senior developer", "Kesempatan diangkat menjadi karyawan tetap", "Laptop dan peralatan kerja"]',
        'https://career.tokopedia.com/internship',
        '2024-03-01',
        '2024-08-31',
        true,
        850,
        NOW(),
        NOW()
    ),
    (
        2,
        'magang-data-analyst-gojek',
        'Data Analyst Intern',
        'Gojek',
        'https://via.placeholder.com/80?text=Gojek',
        'Jakarta',
        '3-6 Bulan',
        3500000,
        5000000,
        'Bergabung dengan data team untuk menganalisis user behavior dan business metrics. Hands-on experience dengan big data dan visualization tools.',
        '["Mahasiswa S1/S2 jurusan Statistika/Matematika/TI", "Menguasai SQL dan Python", "Familiar dengan data visualization tools", "Analytical thinking yang kuat", "Dapat magang minimal 3 bulan"]',
        '["Stipend kompetitif", "Project real impact", "Networking dengan data professionals", "Free lunch & transport", "Flexible working hours"]',
        'https://www.gojek.io/careers',
        '2024-03-15',
        '2024-09-15',
        true,
        1250,
        NOW(),
        NOW()
    ),
    (
        3,
        'magang-ui-ux-designer-bukalapak',
        'UI/UX Designer Intern',
        'Bukalapak',
        'https://via.placeholder.com/80?text=Bukalapak',
        'Jakarta (Remote)',
        '4 Bulan',
        2500000,
        3500000,
        'Opportunity untuk belajar product design di e-commerce platform. Terlibat dalam user research hingga implementasi design system.',
        '["Mahasiswa Desain Komunikasi Visual/Informatika", "Portfolio design project", "Menguasai Figma/Adobe XD", "Memahami UI/UX principles", "Komunikatif dan kolaboratif"]',
        '["Monthly allowance", "Remote work", "Design mentorship", "Access to design tools", "Career development"]',
        'https://careers.bukalapak.com',
        '2024-04-01',
        '2024-07-31',
        true,
        680,
        NOW(),
        NOW()
    ) ON CONFLICT (id) DO NOTHING;

-- Scholarships (Beasiswa)
INSERT INTO
    scholarships (
        id,
        slug,
        title,
        provider,
        provider_logo,
        scholarship_type,
        education_level,
        coverage,
        amount_min,
        amount_max,
        description,
        requirements,
        benefits,
        application_url,
        open_date,
        close_date,
        is_active,
        view_count,
        created_at,
        updated_at
    )
VALUES (
        1,
        'beasiswa-unggulan-kemendikbud-2024',
        'Beasiswa Unggulan Kemendikbudristek 2024',
        'Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi',
        'https://via.placeholder.com/80?text=Kemendikbud',
        'Full Scholarship',
        'S1, S2, S3',
        'Full (Tuition + Living)',
        10000000,
        50000000,
        'Program beasiswa penuh dari pemerintah untuk mahasiswa berprestasi. Mencakup biaya kuliah, biaya hidup, dan tunjangan penelitian.',
        '["WNI berprestasi akademik/non-akademik", "IPK minimal 3.25", "Surat rekomendasi dari kampus", "Essay motivasi", "Proposal studi/penelitian"]',
        '["Biaya kuliah penuh", "Biaya hidup bulanan", "Tunjangan buku", "Asuransi kesehatan", "Biaya penelitian"]',
        'https://beasiswaunggulan.kemdikbud.go.id',
        '2024-02-01',
        '2024-04-30',
        true,
        5600,
        NOW(),
        NOW()
    ),
    (
        2,
        'beasiswa-bni-s1-2024',
        'Beasiswa BNI untuk Mahasiswa S1',
        'PT Bank Negara Indonesia (Persero) Tbk',
        'https://via.placeholder.com/80?text=BNI',
        'Partial Scholarship',
        'S1',
        'Tuition Fee',
        5000000,
        10000000,
        'Beasiswa dari BNI untuk mahasiswa S1 yang kurang mampu namun berprestasi. Fokus pada jurusan ekonomi, teknik, dan sains.',
        '["Mahasiswa aktif S1 semester 2-6", "IPK minimal 3.00", "Dari keluarga kurang mampu", "Aktif berorganisasi", "Surat keterangan tidak mampu"]',
        '["Bantuan biaya kuliah per semester", "Coaching & mentoring", "Kesempatan magang di BNI", "Networking event", "Certificate"]',
        'https://www.bni.co.id/id-id/tentangbni/programcsr/beasiswa',
        '2024-01-15',
        '2024-03-31',
        true,
        3200,
        NOW(),
        NOW()
    ),
    (
        3,
        'beasiswa-lpdp-s2-luar-negeri',
        'Beasiswa LPDP S2 Luar Negeri',
        'Lembaga Pengelola Dana Pendidikan (LPDP)',
        'https://via.placeholder.com/80?text=LPDP',
        'Full Scholarship',
        'S2',
        'Full (Tuition + Living + Travel)',
        0,
        800000000,
        'Beasiswa penuh untuk studi S2 di luar negeri. Mencakup biaya kuliah, hidup, tiket pesawat, dan tunjangan keluarga.',
        '["Lulusan S1 dengan IPK minimal 3.00", "LoA unconditional dari universitas tujuan", "TOEFL/IELTS sesuai ketentuan", "Usia maksimal 42 tahun", "Komitmen kembali ke Indonesia"]',
        '["Biaya pendidikan penuh", "Biaya hidup di luar negeri", "Tiket PP Indonesia-negara tujuan", "Tunjangan buku", "Asuransi kesehatan", "Tunjangan keluarga (jika ada)"]',
        'https://lpdp.kemenkeu.go.id',
        '2024-02-15',
        '2024-05-15',
        true,
        8900,
        NOW(),
        NOW()
    ) ON CONFLICT (id) DO NOTHING;

-- Competitions (Lomba)
INSERT INTO
    competitions (
        id,
        slug,
        title,
        organizer,
        organizer_logo,
        category,
        competition_level,
        prize_total,
        description,
        requirements,
        benefits,
        registration_url,
        registration_open,
        registration_close,
        event_date,
        is_active,
        view_count,
        created_at,
        updated_at
    )
VALUES (
        1,
        'gemastik-xvii-2024',
        'Gemastik XVII 2024',
        'Pusat Prestasi Nasional Kemendikbudristek',
        'https://via.placeholder.com/80?text=Gemastik',
        'IT & Technology',
        'Nasional',
        500000000,
        'Kompetisi teknologi informasi terbesar untuk mahasiswa Indonesia. Berbagai cabang: programming, data mining, IoT, game development, dan lainnya.',
        '["Mahasiswa aktif S1/D3/D4", "Tim 2-3 orang per cabang", "Kartu mahasiswa aktif", "Proposal sesuai cabang lomba", "KTM dan surat tugas kampus"]',
        '["Total hadiah Rp 500 juta", "Sertifikat nasional", "Piagam penghargaan", "Publikasi karya", "Networking dengan praktisi"]',
        'https://gemastik.hmif.tech',
        '2024-03-01',
        '2024-05-31',
        '2024-09-15',
        true,
        4500,
        NOW(),
        NOW()
    ),
    (
        2,
        'business-plan-competition-ui-2024',
        'Business Plan Competition UI 2024',
        'Universitas Indonesia',
        'https://via.placeholder.com/80?text=UI',
        'Business & Entrepreneurship',
        'Nasional',
        100000000,
        'Kompetisi business plan untuk mahasiswa se-Indonesia. Kesempatan pitching ide bisnis di depan investor dan mentor berpengalaman.',
        '["Mahasiswa aktif S1/S2", "Tim 3-5 orang", "Business plan inovatif", "Pitch deck", "Video pitch 3 menit"]',
        '["Juara 1: Rp 50 juta", "Juara 2: Rp 30 juta", "Juara 3: Rp 20 juta", "Mentoring dari praktisi", "Kesempatan funding"]',
        'https://bpc.ui.ac.id',
        '2024-02-20',
        '2024-04-20',
        '2024-07-01',
        true,
        2800,
        NOW(),
        NOW()
    ) ON CONFLICT (id) DO NOTHING;

-- Webinars
INSERT INTO
    webinars (
        id,
        slug,
        title,
        speaker_name,
        speaker_title,
        speaker_photo,
        organizer,
        topic,
        description,
        event_date,
        start_time,
        end_time,
        platform,
        registration_url,
        is_free,
        price,
        max_participants,
        is_active,
        view_count,
        created_at,
        updated_at
    )
VALUES (
        1,
        'cara-membangun-personal-branding-di-linkedin',
        'Cara Membangun Personal Branding di LinkedIn',
        'Sarah Wijaya',
        'HR Manager - Tokopedia',
        'https://via.placeholder.com/100?text=Sarah',
        'KabarKarir x LinkedIn',
        'Career Development',
        'Workshop praktis membangun personal branding yang kuat di LinkedIn. Tips optimasi profil, strategi konten, dan networking effectively.',
        '2024-03-20',
        '19:00:00',
        '21:00:00',
        'Zoom',
        'https://bit.ly/webinar-linkedin-personal-branding',
        true,
        0,
        500,
        true,
        1200,
        NOW(),
        NOW()
    ),
    (
        2,
        'tips-interview-di-startup-unicorn',
        'Tips Interview di Startup Unicorn Indonesia',
        'Budi Santoso',
        'Talent Acquisition Lead - Gojek',
        'https://via.placeholder.com/100?text=Budi',
        'KabarKarir',
        'Interview Preparation',
        'Insight langsung dari recruiter startup unicorn tentang proses interview, pertanyaan yang sering muncul, dan cara membuat kesan yang lasting.',
        '2024-03-25',
        '18:30:00',
        '20:00:00',
        'Google Meet',
        'https://bit.ly/webinar-interview-startup',
        true,
        0,
        300,
        true,
        850,
        NOW(),
        NOW()
    ) ON CONFLICT (id) DO NOTHING;

-- ===========================================
-- 3. FRONTEND-PELATIHAN DATA (LMS)
-- ===========================================

-- Courses
INSERT INTO
    courses (
        id,
        slug,
        title,
        short_description,
        description,
        instructor_name,
        instructor_title,
        instructor_photo,
        category,
        level,
        language,
        duration_hours,
        total_modules,
        total_lessons,
        total_students,
        price,
        discount_price,
        is_free,
        is_published,
        is_featured,
        certificate_available,
        requirements,
        learning_outcomes,
        thumbnail_url,
        preview_video_url,
        average_rating,
        total_reviews,
        created_at,
        updated_at
    )
VALUES (
        1,
        'fullstack-web-developer-bootcamp',
        'Fullstack Web Developer Bootcamp 2024',
        'Belajar web development dari nol hingga mahir. HTML, CSS, JavaScript, React, Node.js, dan database.',
        '<h2>Deskripsi Lengkap</h2><p>Kursus komprehensif untuk menjadi fullstack web developer professional. Mulai dari fundamental HTML/CSS hingga build complete web applications dengan React dan Node.js.</p><h3>Yang Akan Dipelajari</h3><ul><li>Frontend: HTML, CSS, JavaScript, React</li><li>Backend: Node.js, Express, REST API</li><li>Database: MongoDB, PostgreSQL</li><li>Deployment & DevOps</li></ul>',
        'John Doe',
        'Senior Fullstack Developer',
        'https://via.placeholder.com/150?text=John',
        'Web Development',
        'beginner',
        'Bahasa Indonesia',
        120,
        12,
        150,
        5420,
        2999000,
        1499000,
        false,
        true,
        true,
        true,
        '["Laptop/PC dengan spesifikasi minimal", "Koneksi internet stabil", "Tidak perlu pengalaman coding sebelumnya", "Semangat belajar yang tinggi"]',
        '["Membuat website responsive dengan HTML & CSS", "Membangun aplikasi interaktif dengan JavaScript", "Develop modern web apps dengan React", "Create REST API dengan Node.js & Express", "Integrate database MongoDB & PostgreSQL", "Deploy aplikasi ke production"]',
        'https://via.placeholder.com/800x450?text=Fullstack+Bootcamp',
        'https://www.youtube.com/embed/dQw4w9WgXcQ',
        4.8,
        342,
        NOW(),
        NOW()
    ),
    (
        2,
        'data-science-untuk-pemula',
        'Data Science untuk Pemula - Python & Machine Learning',
        'Masuk ke dunia data science dengan Python. Belajar data analysis, visualization, dan machine learning.',
        '<h2>Tentang Kursus Ini</h2><p>Kursus data science yang dirancang khusus untuk pemula. Step by step belajar Python, data analysis dengan Pandas, visualisasi data, dan machine learning basics.</p>',
        'Dr. Amanda Lee',
        'Data Scientist - Gojek',
        'https://via.placeholder.com/150?text=Amanda',
        'Data Science',
        'beginner',
        'Bahasa Indonesia',
        80,
        10,
        120,
        3890,
        1999000,
        999000,
        false,
        true,
        true,
        true,
        '["Laptop dengan RAM minimal 8GB", "Basic programming knowledge (opsional)", "Install Python dan Jupyter Notebook", "Passion untuk data"]',
        '["Master Python untuk data science", "Data manipulation dengan Pandas", "Data visualization dengan Matplotlib & Seaborn", "Statistical analysis fundamentals", "Build machine learning models", "Real-world data science projects"]',
        'https://via.placeholder.com/800x450?text=Data+Science',
        'https://www.youtube.com/embed/dQw4w9WgXcQ',
        4.9,
        289,
        NOW(),
        NOW()
    ),
    (
        3,
        'ui-ux-design-mastery',
        'UI/UX Design Mastery - Dari Figma hingga Portfolio',
        'Panduan lengkap menjadi UI/UX designer. Belajar design thinking, Figma, prototyping, dan user research.',
        '<h2>Kuasai UI/UX Design</h2><p>Kursus lengkap untuk menguasai UI/UX design. Dari teori design thinking, user research, wireframing, hingga high-fidelity design dengan Figma.</p>',
        'Sarah Designer',
        'Lead Product Designer',
        'https://via.placeholder.com/150?text=Sarah',
        'UI/UX Design',
        'intermediate',
        'Bahasa Indonesia',
        60,
        8,
        90,
        2340,
        1499000,
        749000,
        false,
        true,
        false,
        true,
        '["Laptop/PC", "Install Figma (gratis)", "Creative mindset", "Portfolio work (optional)"]',
        '["Design thinking methodology", "User research techniques", "Wireframing & prototyping", "Visual design principles", "Figma mastery", "Build impressive portfolio"]',
        'https://via.placeholder.com/800x450?text=UI+UX+Design',
        'https://www.youtube.com/embed/dQw4w9WgXcQ',
        4.7,
        178,
        NOW(),
        NOW()
    ),
    (
        4,
        'digital-marketing-complete-guide',
        'Digital Marketing Complete Guide 2024',
        'Strategi digital marketing terkini: SEO, SEM, Social Media, Email Marketing, dan Analytics.',
        '<h2>Master Digital Marketing</h2><p>Pelajari semua aspek digital marketing modern. Dari SEO optimization, Google Ads, social media strategy, content marketing, hingga analytics dan reporting.</p>',
        'Michael Marketing',
        'Digital Marketing Manager',
        'https://via.placeholder.com/150?text=Michael',
        'Digital Marketing',
        'beginner',
        'Bahasa Indonesia',
        50,
        7,
        75,
        4120,
        999000,
        499000,
        false,
        true,
        true,
        true,
        '["Laptop/PC dan internet", "Email dan social media accounts", "No prior marketing experience needed"]',
        '["SEO & keyword research", "Google Ads campaigns", "Social media marketing strategy", "Content marketing", "Email marketing automation", "Analytics & data interpretation"]',
        'https://via.placeholder.com/800x450?text=Digital+Marketing',
        'https://www.youtube.com/embed/dQw4w9WgXcQ',
        4.6,
        256,
        NOW(),
        NOW()
    ),
    (
        5,
        'mobile-app-development-flutter',
        'Mobile App Development dengan Flutter',
        'Buat aplikasi mobile iOS & Android dengan satu codebase menggunakan Flutter dan Dart.',
        '<h2>Develop Mobile Apps</h2><p>Kursus praktis membangun mobile applications dengan Flutter. Dari setup environment hingga publish app ke Google Play Store dan App Store.</p>',
        'Kevin Mobile',
        'Mobile Developer - Tokopedia',
        'https://via.placeholder.com/150?text=Kevin',
        'Mobile Development',
        'intermediate',
        'Bahasa Indonesia',
        70,
        9,
        100,
        1890,
        1799000,
        899000,
        false,
        true,
        false,
        true,
        '["Laptop dengan RAM minimal 8GB", "Install Flutter SDK", "Basic programming knowledge", "Android Studio atau VS Code"]',
        '["Flutter framework fundamentals", "Dart programming language", "Build responsive UI", "State management", "API integration", "Publish to App Store & Play Store"]',
        'https://via.placeholder.com/800x450?text=Flutter+Development',
        'https://www.youtube.com/embed/dQw4w9WgXcQ',
        4.8,
        145,
        NOW(),
        NOW()
    ),
    (
        6,
        'intro-to-programming-python',
        'Pengantar Programming dengan Python - Gratis',
        'Kursus gratis untuk memulai journey programming. Belajar Python dari nol dengan praktek langsung.',
        '<h2>Mulai Belajar Programming</h2><p>Kursus gratis yang perfect untuk pemula absolute. Belajar fundamental programming dengan bahasa Python yang mudah dipahami.</p>',
        'Lisa Beginner',
        'Python Instructor',
        'https://via.placeholder.com/150?text=Lisa',
        'Web Development',
        'beginner',
        'Bahasa Indonesia',
        30,
        5,
        50,
        8750,
        0,
        0,
        true,
        true,
        true,
        true,
        '["Laptop/PC", "Install Python (akan dipandu)", "Tidak perlu background IT", "Konsisten belajar"]',
        '["Programming basics", "Python syntax", "Variables & data types", "Control flow", "Functions", "Basic projects"]',
        'https://via.placeholder.com/800x450?text=Python+Intro',
        'https://www.youtube.com/embed/dQw4w9WgXcQ',
        4.9,
        567,
        NOW(),
        NOW()
    ) ON CONFLICT (id) DO NOTHING;

-- Course Modules & Lessons (Sample for Course 1)
INSERT INTO
    course_modules (
        id,
        course_id,
        title,
        description,
        order_index,
        created_at,
        updated_at
    )
VALUES (
        1,
        1,
        'Introduction & Setup',
        'Pengenalan web development dan setup development environment',
        1,
        NOW(),
        NOW()
    ),
    (
        2,
        1,
        'HTML Fundamentals',
        'Belajar struktur dasar HTML dan semantic elements',
        2,
        NOW(),
        NOW()
    ),
    (
        3,
        1,
        'CSS Mastery',
        'Styling website dengan CSS modern dan responsive design',
        3,
        NOW(),
        NOW()
    ) ON CONFLICT (id) DO NOTHING;

INSERT INTO
    course_lessons (
        id,
        module_id,
        title,
        description,
        video_url,
        video_type,
        video_duration_minutes,
        order_index,
        is_preview,
        created_at,
        updated_at
    )
VALUES (
        1,
        1,
        'Welcome & Course Overview',
        'Pengenalan kursus dan roadmap pembelajaran',
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'youtube',
        10,
        1,
        true,
        NOW(),
        NOW()
    ),
    (
        2,
        1,
        'Install VS Code & Extensions',
        'Setup code editor dan extensions yang diperlukan',
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'youtube',
        15,
        2,
        true,
        NOW(),
        NOW()
    ),
    (
        3,
        2,
        'HTML Basics - Tags & Elements',
        'Memahami struktur HTML dan elemen dasar',
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'youtube',
        20,
        1,
        false,
        NOW(),
        NOW()
    ),
    (
        4,
        2,
        'Semantic HTML',
        'Penggunaan semantic tags untuk struktur yang baik',
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'youtube',
        18,
        2,
        false,
        NOW(),
        NOW()
    ) ON CONFLICT (id) DO NOTHING;

-- ================================================
-- SEQUENCE RESET (Optional - untuk auto increment)
-- ================================================
-- Uncomment jika diperlukan
-- SELECT setval('companies_id_seq', (SELECT MAX(id) FROM companies));
-- SELECT setval('jobs_id_seq', (SELECT MAX(id) FROM jobs));
-- SELECT setval('blog_posts_id_seq', (SELECT MAX(id) FROM blog_posts));
-- SELECT setval('internships_id_seq', (SELECT MAX(id) FROM internships));
-- SELECT setval('scholarships_id_seq', (SELECT MAX(id) FROM scholarships));
-- SELECT setval('competitions_id_seq', (SELECT MAX(id) FROM competitions));
-- SELECT setval('webinars_id_seq', (SELECT MAX(id) FROM webinars));
-- SELECT setval('courses_id_seq', (SELECT MAX(id) FROM courses));
-- SELECT setval('course_modules_id_seq', (SELECT MAX(id) FROM course_modules));
-- SELECT setval('course_lessons_id_seq', (SELECT MAX(id) FROM course_lessons));

-- ================================================
-- END OF DUMMY DATA
-- ================================================
-- Total Records:
-- - Companies: 10
-- - Jobs: 10
-- - Blog Posts: 3
-- - Internships: 3
-- - Scholarships: 3
-- - Competitions: 2
-- - Webinars: 2
-- - Courses: 6
-- - Course Modules: 3
-- - Course Lessons: 4
-- ================================================